// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcBuPFK86WRUFFLcHTsU1NGQ727UJHj4c',
    appId: '1:111171024102:web:6aa6045255cbfe6a27f727',
    messagingSenderId: '111171024102',
    projectId: 'githubclone-a3d95',
    authDomain: 'githubclone-a3d95.firebaseapp.com',
    storageBucket: 'githubclone-a3d95.appspot.com',
    measurementId: 'G-W35N2G0GBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCauTXWRGk9wiLNo4BKNLpFReCyzSPEhrY',
    appId: '1:111171024102:android:b8236fbcc50c915227f727',
    messagingSenderId: '111171024102',
    projectId: 'githubclone-a3d95',
    storageBucket: 'githubclone-a3d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGRUFcqW8VWPcLFmflrKs_61Ied8ock4',
    appId: '1:111171024102:ios:c8a574f1cb1ec99227f727',
    messagingSenderId: '111171024102',
    projectId: 'githubclone-a3d95',
    storageBucket: 'githubclone-a3d95.appspot.com',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGRUFcqW8VWPcLFmflrKs_61Ied8ock4',
    appId: '1:111171024102:ios:c8a574f1cb1ec99227f727',
    messagingSenderId: '111171024102',
    projectId: 'githubclone-a3d95',
    storageBucket: 'githubclone-a3d95.appspot.com',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcBuPFK86WRUFFLcHTsU1NGQ727UJHj4c',
    appId: '1:111171024102:web:16340b8a87661e2927f727',
    messagingSenderId: '111171024102',
    projectId: 'githubclone-a3d95',
    authDomain: 'githubclone-a3d95.firebaseapp.com',
    storageBucket: 'githubclone-a3d95.appspot.com',
    measurementId: 'G-CL62CHFWL4',
  );
}
